<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)-windows7.0</TargetFramework>
    <DisableTransitiveFrameworkReferences>true</DisableTransitiveFrameworkReferences>
    <AssemblyName>System.Windows.Forms.Interop.Tests</AssemblyName>
    <Platforms>x86;x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- Native tests do not compile in unified-build - https://github.com/dotnet/source-build/issues/4875 -->
    <ExcludeFromBuild Condition="'$(DotNetBuild)' == 'true'">true</ExcludeFromBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\System.Windows.Forms.csproj" />
    <ProjectReference Include="..\TestUtilities\System.Windows.Forms.TestUtilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <NativeProjectReference Include="NativeTests\CMakeLists.txt" CMakeProject="NativeTests\NativeTests.proj" BuildNative="true" />
  </ItemGroup>

  <Target Name="CopyTlbProjectFiles" BeforeTargets="CopyNativeProjectBinaries">
    <ItemGroup>
      <NativeProjectBinaries Include="$(NativeProjectOutputFolder)\*.tlb" />
      <NativeProjectBinaries Include="$(NativeProjectOutputFolder)\*.manifest" />
    </ItemGroup>
  </Target>

</Project>
